### ISSUE TITLE
write_trace does not work

### ISSUE THREAD

**Issue by redpublic** [slfritchie/eflame#3]
Am i doing it wrong or something broken?
`:eflame2.write_trace(:global_calls_plus_new_procs, "/tmp/eflame.trace", :all, 10*1000)
** (MatchError) no match of right hand side value: {:error, {:badarg, [{:erlang, :++, ["/tmp/eflame.trace", []], []}, {:dbg, :"-trace_port1/3-fun-1-", 2, [file: 'dbg.erl', line: 472]}, {:dbg, :loop, 2, [file: 'dbg.erl', line: 678]}]}}
    src/eflame2.erl:36: :eflame2.write_trace2/7
`

Running from elixir
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
IEx 1.3.2

**Comment by slfritchie** [comment]
I'm not sure, sorry.  I've not yet tried using Erlang/OTP 19 + eflame.

**Comment by redpublic** [comment]
Was my bad, incorrect format of the passed parameters, file should be enclosed in single quotes
